"""add page extraction method

Revision ID: 5dc00aeb1959
Revises: 2cfc3752d81d
Create Date: 2026-09-01 23:16:18.036822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc00aeb1959'
down_revision: Union[str, Sequence[str], None] = '2cfc3752d81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'document_pages',
    sa.Column(
        'extraction_method',
        sa.String(),
        nullable=False,
        server_default='unknown'
    )
)

    op.alter_column(
        'document_pages',
        'extraction_method',
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_pages', 'extraction_method')
    # ### end Alembic commands ###
