"""add_classification_fields

Revision ID: cf538797a342
Revises: 5dc00aeb1959
Create Date: 2026-09-07 22:56:43.533204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf538797a342'
down_revision: Union[str, Sequence[str], None] = '5dc00aeb1959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('classified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'classified_at')
    op.drop_column('documents', 'classification_confidence')
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###
